教师查询某一problemset成绩，修改接口
EduOJ/backend pull request #142
Opened 2024-05-06 11:28 UTC by qianxi66

实现#132 的
Class管理员，查询该Class中某一ProblemSet的全部用户成绩 需求。
继承#133pr的代码写的。

2024-06-25 07:16 UTC, leoleoasd requested changes

2024-06-25 07:16 UTC, leoleoasd commented on base/utils/problem_set.go
> +
Please write comments in English

2024-06-26 14:10 UTC, leoleoasd approved these changes
LGTM

2024-06-26 20:21 UTC, qianxi66 commented
I have read the CLA Document and I hereby sign the CLA

2024-06-30 13:46 UTC, leoleoasd approved these changes
LGTM

2024-06-30 13:47 UTC, merged