Finished "GetGrades" API.
EduOJ/backend pull request #81
Opened 2021-04-21 13:20 UTC by lbh2001

下午看到这个项目大概理清一下源码逻辑之后，试着先finish了第一个API(GetGrades)，希望指出一下不正之处。

2021-04-21 13:36 UTC, leoleoasd requested changes

2021-04-21 13:36 UTC, leoleoasd commented on app/response/resource/problem_set.go
> +	Grades   []Grade          `json:"Grades"`
json的key使用snake_case.

2021-04-21 13:36 UTC, leoleoasd commented on app/routes.go
> +	manageProblemSet.GET("/class/:class_id/problem_set/:id/grades", controller.GetGrades,
这个路由不需要manage_problem_sets权限，因此不应该放在manageProblemSet这个group下面。
应该单独弄一个需要read_answers的group。

2021-04-21 13:36 UTC, leoleoasd commented on app/controller/problem_set.go
> +	class := models.Class{}
需要编写单元测试。

2021-04-21 13:36 UTC, leoleoasd commented on app/controller/problem_set.go
> +				resource.GetGrades(&problemSet),
注意需求：对于没有提交过的学生创建0分Grade。

2021-04-21 13:37 UTC, leoleoasd commented
@suntt2019 review一下这个？有啥其他意见吗？

2021-04-21 13:42 UTC, leoleoasd commented
@lbh2001 同时，我需要提醒你一下：OSPP的选拔**不以**是否给项目做过贡献为决定性因素。给项目发pr可以证明你有完成项目的能力，但是起到决定性因素的还是你的proposal里的方案设计。

2021-04-21 13:45 UTC, lbh2001 commented
> @lbh2001 同时，我需要提醒你一下：OSPP的选拔**不以**是否给项目做过贡献为决定性因素。给项目发pr可以证明你有完成项目的能力，但是起到决定性因素的还是你的proposal里的方案设计。

是的，我清楚这一点。我也只是想以这种方式初步了解这个项目，毕竟了解项目后再设计方案会更加顺利，如果能混个脸熟就更好了(笑)

2021-04-21 13:46 UTC, leoleoasd commented
> > @lbh2001 同时，我需要提醒你一下：OSPP的选拔**不以**是否给项目做过贡献为决定性因素。给项目发pr可以证明你有完成项目的能力，但是起到决定性因素的还是你的proposal里的方案设计。
> 
> 是的，我清楚这一点。我也只是想以这种方式初步了解这个项目，毕竟了解项目后再设计方案会更加顺利，如果能混个脸熟就更好了(笑)

了解了就好，我是有过一次GSOC因为“没有给项目做出足够的贡献“被拒的经历，所以提醒你一下 :joy:

2021-04-21 14:48 UTC, lbh2001 commented on app/controller/problem_set.go
> +				resource.GetGrades(&problemSet),
那是需要使用`model.User`吗？通过`model.User`中的`Grade`中的`ProblemSetId`与传入的`id`相等作为查询条件，查询`model.User`中的`Grade`中的`total`，如果查到了那么就直接用这条`Grade`，如果没有那么就新建一条`total`为 0 的`Grade`作为一条返回数据（并不真正持久化到数据库）。似乎像我代码中那样查到的只是已有的`Grade`的数据，具体哪些用户没有`Grade`并不能直接得到。

2021-04-21 14:50 UTC, leoleoasd commented on app/controller/problem_set.go
> +				resource.GetGrades(&problemSet),
@lbh2001
1. 解决完问题之前不要mark as resolved
2. 这个api是给老师查询某次作业的全部成绩用的。需要给班级里的没有提交过代码的同学创建空的grade。跟user没关系？🤔

2021-04-21 14:55 UTC, lbh2001 commented on app/controller/problem_set.go
> +				resource.GetGrades(&problemSet),
抱歉点回复的时候手误点到了Resolve，ok我再尝试一下。

2021-04-21 15:49 UTC, leoleoasd commented
@lbh2001 请在本地运行
git fetch origin
git rebase origin/master
git push -f
来同步到主分支。不要merge。

2021-04-21 15:51 UTC, leoleoasd requested changes

2021-04-21 15:51 UTC, leoleoasd commented on app/controller/problem_set.go
> +	if err := base.DB.Preload("Students").First(students, c.Param("class_id")).Error; err != nil {
你提交代码之前真的运行/测试过吗？
请看一下gorm文档。

2021-04-21 15:53 UTC, leoleoasd commented on app/controller/problem_set.go
> +	if err := base.DB.Preload("Students").First(students, c.Param("class_id")).Error; err != nil {
提交的代码，至少你真的运行过，是最基本的吧。

2021-04-21 16:45 UTC, lbh2001 commented on app/controller/problem_set.go
> +	if err := base.DB.Preload("Students").First(students, c.Param("class_id")).Error; err != nil {
`First`这里我cv其他地方的时候忘了改。。很尴尬
抱歉我之前确实没有测试过代码，我也是刚刚才知道go test。。
刚刚大概看了一下你的一些test文件内容，大概明白了一点该怎么测试。
等我起床试试吧，感谢教导^_^

2021-04-22 00:06 UTC, leoleoasd commented on app/controller/problem_set.go
> +	if err := base.DB.Preload("Students").First(students, c.Param("class_id")).Error; err != nil {
提交代码，不说单元测试，至少在自己电脑上编译过运行过是最基本的吧。
go test的单元测试是更高要求了。

2021-04-22 00:07 UTC, leoleoasd commented on app/controller/problem_set.go
> +	if err := base.DB.Preload("Students").First(students, c.Param("class_id")).Error; err != nil {
以及，项目要求所有提交都有gpg签名。请google一下该怎么做。
再以及，项目要求pr的提交里，每一部分代码和对应的单元测试在同一个提交里提交（保证每一个提交的节点上的测试都是完整的）。你写完测试需要rebase。

2021-04-22 02:16 UTC, leoleoasd commented on app/controller/problem_set.go
> +		for i := 0; i < studentsLen; i++ {
这里可以O（n）处理吧。
用map

2021-04-22 13:04 UTC, leoleoasd requested changes

2021-04-22 13:04 UTC, leoleoasd commented on app/response/resource/problem_set.go
> +	Grades   []Grade          `json:"snake_case"`
这都不知道，说明你缺少最基本的程序常识。
开源项目不是你练手的地方。review你的pr并指导是很费精力的。麻烦换个地方练手吧。

2021-04-22 13:04 UTC, closed without merging

2021-04-22 14:18 UTC, leoleoasd reviewed
这个代码问题太多了。

2021-04-22 14:18 UTC, leoleoasd commented on app/controller/problem_set_test.go
> +		assert.NoError(t, base.DB.Save(&problemSet).Error)
这行在干啥？

2021-04-22 14:18 UTC, leoleoasd commented on app/controller/problem_set_test.go
> +		user.GrantRole("class_creator", class)
应该放到函数的最开头

2021-04-22 14:18 UTC, leoleoasd commented on app/controller/problem_set_test.go
> +		resp.Data.Grades = []resource.Grade{}
？
非常离谱
你的测试要判断响应的结果对不对
你的标准答案是错的（应该有grade，你的problemsets里没grade）
你把考生的答案也改成错的然后比较
考生的答案就和标准答案一样了？？

2021-04-22 14:18 UTC, leoleoasd commented on app/controller/problem_set_test.go
> +		assert.NoError(t, utils.UpdateGrade(&models.Submission{
单元测试，除了调用被测试的函数之外，不应该调用其他东西。
比如不应该调用updategrade，应该手动创建/修改grade。
你这个update grade根本没创建grade。
这个函数会判断problem set是否结束了，结束了之后的提交不统计分数。
上面测试创建的problemset已经结束了。

所以你下面problemset的grades才是空。

2021-04-22 14:18 UTC, leoleoasd commented on app/controller/problem_set.go
> +		First(&problemSet, "id = ? and class_id = ?", c.Param("id"), c.Param("class_id")).Error; err != nil {
需要preload problems，以便在下面创建grade的detail的时候让每个problem的grade都是0。