Again
EduOJ/backend pull request #88
Opened 2021-04-23 04:55 UTC by lbh2001

2021-04-23 04:58 UTC, lbh2001 commented
> _No description provided._

我把部分代码再好好读了一遍，发现之前确实理解的太离谱了（测试的逻辑方面）
按照你的review重新完成了测试，这次应该大体上是正确的。
目前有个问题就是我并不知道如何通过你们的BeforeSave自动求Total
所以我在actual和expect的problemSet的Grade里都手动设置了total=0

2021-04-23 05:00 UTC, leoleoasd commented
> > _No description provided._
> 
> 我把部分代码再好好读了一遍，发现之前确实理解的太离谱了（测试的逻辑方面）
> 按照你的review重新完成了测试，这次应该大体上是正确的。
> 目前有个问题就是我并不知道如何通过你们的BeforeSave自动求Total
> 所以我在actual和expect的problemSet的Grade里都手动设置了total=0
@lbh2001 
首先，你还是没有修复git历史。
其次，第二个问题请看gorm文档。

2021-04-23 05:05 UTC, leoleoasd requested changes
你的代码达不到我们对于代码质量的要求。请先在别的地方熟悉gorm/单元测试等工具的使用。

2021-04-23 05:05 UTC, leoleoasd commented on app/controller/problem_set.go
> +				Detail:       datatypes.JSON{},
请再仔细看一遍我昨天的每一条review。
这里显然是错的。

2021-04-23 05:05 UTC, leoleoasd commented on app/controller/problem_set.go
> +	base.DB.Save(problemSet)
昨天你的problemset是指针，就直接save
你既然改成了是值，就得取地址。

2021-04-23 05:05 UTC, leoleoasd commented on app/controller/problem_set_test.go
> +		user := createUserForTest(t, "get_grades_success", 0)
需要语义化命名，如classCreator

2021-04-23 05:05 UTC, leoleoasd commented on app/controller/problem_set_test.go
> +			ID:           0,
逻辑还是错的。
只测了一半的逻辑。

2021-04-23 05:12 UTC, leoleoasd commented on app/controller/problem_set_test.go
> +			ID:           0,
你只测了 对于没有提交，创建0分grade并返回。
没有测试这个0分grade是否被写到了数据库里
没有测试别的有分数的grade是否行为正确。

一个合理的测试，应该能够保证删掉/改掉被测试代码的任意部分后，测试都能发现。

2021-04-25 11:13 UTC, leoleoasd commented
@lbh2001 有更新吗？

2021-04-25 11:21 UTC, lbh2001 commented
最近在备考期中，过2天看看



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 25, 2021 19:13 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [EduOJ/backend] Again (#88)




 
@lbh2001 有更新吗？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-04-25 11:22 UTC, leoleoasd commented
> 最近在备考期中，过2天看看
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sun, Apr 25, 2021 19:13 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [EduOJ/backend] Again (#88) @lbh2001 有更新吗？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

好的

2021-05-21 02:52 UTC, leoleoasd commented
@lbh2001 有更新吗？

2021-05-21 14:19 UTC, leoleoasd commented
closing due to inactivity.

2021-05-21 14:19 UTC, closed without merging